// swift-tools-version: 6.1

import PackageDescription

// Compiles the *migrated* legacy showcase against the new library. The test target's source is
// generated by `migrate-and-build.sh` (the real migrator run over `Legacy/*.fixture`) and is
// gitignored — this package has no committed Swift of its own on purpose.
let package = Package(
  name: "MigrationProof",
  platforms: [.macOS(.v15), .iOS(.v15)],
  dependencies: [
    // TODO: pin to a version tag once the native API ships. On a branch until then.
    .package(url: "https://github.com/adammcarter/swift-snapshot-testing-macros", branch: "snapshot-helpers")
  ],
  targets: [
    .testTarget(
      name: "ShowcaseTests",
      dependencies: [
        .product(name: "SnapshotTestingMacros", package: "swift-snapshot-testing-macros")
      ]
    )
  ]
)
